# Generated by Django 5.2 on 2025-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='el nombre del producto', max_length=100)),
                ('descripcion', models.CharField(help_text='la descripcion', max_length=200, null=True)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
