# Generated by Django 5.2 on 2025-10-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_producto_delete_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inventory'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
