# Generated by Django 5.2 on 2025-10-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_producto_imagen_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
